# Generated by Django 5.1 on 2024-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_supplier_status_alter_supplier_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="debts",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="задолженность перед поставщиком",
            ),
        ),
    ]
