# Generated by Django 5.1 on 2024-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_alter_supplier_debts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="debts",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=20,
                null=True,
                verbose_name="задолженность перед поставщиком",
            ),
        ),
    ]
