# Generated by Django 5.1 on 2024-08-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0004_alter_supplier_debts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="status",
            new_name="type",
        ),
        migrations.AddField(
            model_name="supplier",
            name="level",
            field=models.SmallIntegerField(default=0, verbose_name="уровень"),
        ),
    ]
