# Generated by Django 5.1 on 2024-08-14 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0005_rename_status_supplier_type_supplier_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="city",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="country",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="email",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="house",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="street",
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="улица"
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="номер дома"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplier",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
