# Generated by Django 5.1 on 2024-08-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0006_remove_supplier_city_remove_supplier_country_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="Contact",
        ),
    ]
